#!/bin/sh -e
. /usr/share/debconf/confmodule

db_get ocp/short_name
aq=$RET
echo "Shortname $aq is used to create png" >> /tmp/postinst

convert -size 30x30 label:"$aq" "/usr/share/icons/$aq.png"

db_get ocp/printers
pn=$RET

desktop="[Desktop Entry]\nName=Print_Barcode_$pn\nGenericName=Print Barcode in $pn\nTryExec=/usr/bin/print_barcode_$pn\nExec=/usr/bin/print_barcode_$pn\nTerminal=false\nType=Application\nKeywords=print;\nIcon=barcode.png\nCategories=Utility;Office;\nStartupNotify=false"
echo $desktop > "/usr/share/applications/ocp_print_$pn.desktop"
